"""Generates all human-readable documentation for the generated team package."""
from __future__ import annotations

from datetime import datetime, timezone

from team_maker.domain.models import GeneratedTeam


class DocsGenerator:
    """Produces markdown documentation files for the generated team."""

    # ------------------------------------------------------------------
    # Top-level README
    # ------------------------------------------------------------------

    def render_readme(self, team: GeneratedTeam) -> str:
        roles_table = self._roles_table(team)
        tasks_list = self._tasks_list(team)
        constraints_block = (
            "\n".join(f"- {c}" for c in team.constraints) if team.constraints else "_None specified._"
        )
        stack_line = f"**Stack:** {team.stack}" if team.stack else ""

        return f"""\
# {team.team_name}

> {team.purpose}

{stack_line}

**Template:** `{team.template_used}`
**Documentation level:** `{team.documentation_level}`
**Generated:** {self._now()}

---

## Agents

{roles_table}

## Workflow Tasks

{tasks_list}

## Constraints

{constraints_block}

---

## Quick Start

```bash
# 1. Install dependencies (CrewAI or compatible framework)
pip install crewai

# 2. Set your API key environment variables (see docs/model_routing.md)
export ANTHROPIC_API_KEY="your-key-here"

# 3. Run the example script
python run_example.py
```

## Documentation

| File | Purpose |
|------|---------|
| `docs/how_to_run.md` | Running the team end-to-end |
| `docs/how_to_extend.md` | Adding agents, tasks, or tools |
| `docs/model_routing.md` | Changing LLM providers per agent |
| `generation_report.md` | What was generated and any warnings |

---

*This team was generated by [team_maker](https://github.com/your-org/team_maker) and is fully independent of it.*
"""

    # ------------------------------------------------------------------
    # How-to-run guide
    # ------------------------------------------------------------------

    def render_how_to_run(self, team: GeneratedTeam) -> str:
        agent_env_vars = self._agent_env_vars(team)
        return f"""\
# How to Run: {team.team_name}

## Prerequisites

- Python 3.11+
- `crewai` installed (`pip install crewai`)
- API key environment variables set (see below)

## Environment Variables

{agent_env_vars}

## Running the Example

```bash
python run_example.py
```

This script loads `team_config.yaml`, instantiates each agent defined in `agents/`,
and executes the workflow defined in `tasks/`.

## Running with Custom Input

Edit `run_example.py` and pass your own `goal` string to the crew.

## Running Individual Agents

Each agent config in `agents/` is self-contained.  You can instantiate a single
agent like this:

```python
import yaml
from crewai import Agent

with open("agents/architect.yaml") as f:
    cfg = yaml.safe_load(f)

agent = Agent(
    role=cfg["role"],
    goal=cfg["goal"],
    backstory=cfg["backstory"],
)
```

## Workflow Order

The tasks in `tasks/` have explicit `dependencies` fields.  The framework
(CrewAI or compatible) resolves the execution order automatically.

If you need a linear list:

{self._task_order_list(team)}
"""

    # ------------------------------------------------------------------
    # How-to-extend guide
    # ------------------------------------------------------------------

    def render_how_to_extend(self, team: GeneratedTeam) -> str:
        return f"""\
# How to Extend: {team.team_name}

## Adding a New Agent

1. Create a new file in `agents/`, e.g. `agents/security_engineer.yaml`.
2. Use an existing agent file as a template.
3. Add the new agent's role to `team_config.yaml` under `agents`.
4. (Optional) Add it to `docs/model_routing.md` with the desired LLM.
5. Update `run_example.py` to include the new agent in the crew.

### Minimal agent YAML

```yaml
role: security_engineer
display_name: Security Engineer
description: Reviews the codebase for security vulnerabilities and advises on hardening.
goal: Identify and remediate security risks before they reach production.
backstory: |
  A former red-teamer turned defender with deep knowledge of OWASP Top 10,
  threat modelling, and secure-by-default design patterns.
capabilities:
  - security_review
  - threat_modelling
  - penetration_testing
tools:
  - static_analyser
  - dependency_checker
llm:
  provider: anthropic
  model: claude-sonnet-4-6
  api_key_env: ANTHROPIC_API_KEY
is_optional: false
```

## Adding a New Task

1. Create a new file in `tasks/`, e.g. `tasks/security_audit.yaml`.
2. Set `agent_role` to an existing role defined in `agents/`.
3. List any prerequisite task names in `dependencies`.

### Minimal task YAML

```yaml
name: security_audit
description: Audit the codebase for vulnerabilities and produce a remediation plan.
expected_output: Security report with CVSS scores and prioritised fix list.
agent_role: security_engineer
dependencies:
  - code_review
is_optional: false
```

## Swapping the LLM for an Agent

Edit the `llm` block in the relevant `agents/<role>.yaml`:

```yaml
llm:
  provider: openai
  model: gpt-4o
  api_key_env: OPENAI_API_KEY
```

See `docs/model_routing.md` for all available routing options.

## Adding Tools

Add tool names to the `tools` list in the agent YAML.  The tool must be
registered in your framework runtime (e.g. CrewAI tool registry).

## Changing the Workflow

Edit task `dependencies` to reorder execution.  Removing a dependency means
that task can run in parallel with the task it previously waited on.
"""

    # ------------------------------------------------------------------
    # Model routing guide
    # ------------------------------------------------------------------

    def render_model_routing(self, team: GeneratedTeam) -> str:
        rows = "\n".join(
            f"| `{a.role}` | `{a.routing.provider}` | `{a.routing.model}` "
            f"| `{a.routing.api_key_env or 'N/A'}` |"
            for a in team.agents
        )

        return f"""\
# Model / Provider Routing: {team.team_name}

Each agent has its own LLM assignment defined in `agents/<role>.yaml` under
the `llm` key.  A global fallback can also be set in `team_config.yaml`.

## Current Routing Table

| Role | Provider | Model | API Key Env Var |
|------|----------|-------|-----------------|
{rows}

## Supported Providers

| Provider | Example Model IDs |
|----------|-------------------|
| `anthropic` | `claude-opus-4-7`, `claude-sonnet-4-6`, `claude-haiku-4-5` |
| `openai` | `gpt-4o`, `gpt-4o-mini`, `o1-preview` |
| `ollama` | `llama3.2`, `mistral`, `deepseek-coder` |
| `groq` | `llama-3.1-70b-versatile`, `mixtral-8x7b-32768` |
| `google` | `gemini-1.5-pro`, `gemini-flash-1.5` |

## Changing a Route

Edit `agents/<role>.yaml`:

```yaml
llm:
  provider: openai
  model: gpt-4o-mini
  api_key_env: OPENAI_API_KEY
```

Then set the environment variable before running:

```bash
export OPENAI_API_KEY="sk-..."
python run_example.py
```

## Using a Local Model (Ollama)

```yaml
llm:
  provider: ollama
  model: llama3.2
  # No api_key_env needed for local Ollama
```

Ensure Ollama is running locally: `ollama serve`
"""

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _roles_table(self, team: GeneratedTeam) -> str:
        header = "| Role | Display Name | Provider / Model | Optional |\n|------|-------------|-----------------|---------|"
        rows = "\n".join(
            f"| `{a.role}` | {a.display_name} | "
            f"`{a.routing.provider}/{a.routing.model}` | "
            f"{'Yes' if a.is_optional else 'No'} |"
            for a in team.agents
        )
        return header + "\n" + rows

    def _tasks_list(self, team: GeneratedTeam) -> str:
        lines = []
        for t in team.tasks:
            deps = ", ".join(f"`{d}`" for d in t.dependencies) if t.dependencies else "_none_"
            lines.append(f"- **`{t.name}`** → agent: `{t.agent_role}`, depends on: {deps}")
        return "\n".join(lines)

    def _agent_env_vars(self, team: GeneratedTeam) -> str:
        seen: dict[str, str] = {}
        for a in team.agents:
            env = a.routing.api_key_env
            if env and env not in seen:
                seen[env] = a.routing.provider
        if not seen:
            return "_No API keys required (local models only)._"
        lines = ["```bash"]
        for env, provider in seen.items():
            lines.append(f'export {env}="your-{provider}-api-key-here"')
        lines.append("```")
        return "\n".join(lines)

    def _task_order_list(self, team: GeneratedTeam) -> str:
        lines = []
        for i, t in enumerate(team.tasks, 1):
            lines.append(f"{i}. `{t.name}` (agent: `{t.agent_role}`)")
        return "\n".join(lines)

    @staticmethod
    def _now() -> str:
        return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
