"""Generates the generation_report.md artifact."""
from __future__ import annotations

from datetime import datetime, timezone
from typing import List

from team_maker.domain.models import GeneratedTeam
from team_maker.schema.request import TeamCreationRequest
from team_maker.validation.validator import ValidationResult


class ReportGenerator:
    """Produces a human-readable generation report."""

    def render(
        self,
        team: GeneratedTeam,
        request: TeamCreationRequest,
        artifact_paths: List[str],
        validation: ValidationResult,
    ) -> str:
        status_icon = "✅" if validation.passed else "❌"
        issues_block = (
            "\n".join(f"- {issue}" for issue in validation.issues)
            if validation.issues
            else "_No issues found._"
        )
        warnings_block = (
            "\n".join(f"- {w}" for w in validation.warnings)
            if validation.warnings
            else "_No warnings._"
        )
        files_block = "\n".join(f"- `{p}`" for p in sorted(artifact_paths))
        agents_block = "\n".join(
            f"- `{a.role}` → {a.routing.provider}/{a.routing.model}" for a in team.agents
        )
        tasks_block = "\n".join(f"- `{t.name}`" for t in team.tasks)

        return f"""\
# Generation Report

**Team:** {team.team_name}
**Template:** `{team.template_used}`
**Generated:** {self._now()}
**Validation status:** {status_icon} {"PASSED" if validation.passed else "FAILED"}

---

## Input Summary

| Field | Value |
|-------|-------|
| Purpose | {team.purpose[:80]}{"..." if len(team.purpose) > 80 else ""} |
| Stack | {team.stack or "_not specified_"} |
| Documentation level | `{team.documentation_level}` |
| Roles requested | {len(team.agents)} |
| Tasks generated | {len(team.tasks)} |

## Generated Agents

{agents_block}

## Generated Tasks

{tasks_block}

## Generated Files

{files_block}

---

## Validation

### Issues

{issues_block}

### Warnings

{warnings_block}

---

*Generated by team_maker v{self._version()}*
"""

    @staticmethod
    def _now() -> str:
        return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    @staticmethod
    def _version() -> str:
        try:
            from team_maker import __version__
            return __version__
        except ImportError:
            return "unknown"
