"""The only code that loads a generated package's tool module (spec FR-024,
D-3; contracts/tool-resolver-port.md).

FR-084: a package generated before this remediation, whose tool module has
the pre-remediation shape, MUST be detected and refused with an actionable
message rather than loaded, adapted or partially executed under assumed
controls.

Detection scans source text rather than importing the module — a malformed
or hostile pre-remediation module is never executed just to find out what it
is. Shape is defined structurally, not by version number (no such field
exists in a generated package): every current-shape module defines
`ToolPolicyRefusal` (this remediation's marker for a raised, never-stubbed,
never-caught-and-downgraded refusal) and none defines the `SANDBOX_ENABLED` /
`USE_SANDBOX` opt-out toggle this remediation deletes outright (D-7).
"""
from __future__ import annotations

import importlib
import re
import sys
import warnings
from collections.abc import Sequence
from pathlib import Path
from typing import Any, Optional

from team_maker.keyconfig import KeyConfig
from team_maker.ports.tool_resolver import (
    ResolvedTool,
    ToolPolicyError,
    ToolResolver,
    UnknownToolError,
    UnresolvableToolError,
)
from team_maker.tools.catalog import CONDITIONALLY_AVAILABLE_TOOL_NAMES, TOOL_CATALOG

_REQUIRED_MARKER = "class ToolPolicyRefusal"
# Assignment-shaped patterns only — the current template's own docstring and
# comments *name* SANDBOX_ENABLED in prose explaining why it was removed, so
# a bare substring check would false-positive on the fixed template itself.
_FORBIDDEN_PATTERNS = (
    re.compile(r"\bUSE_SANDBOX\s*="),
    re.compile(r"""os\.environ\.get\(\s*["']SANDBOX_ENABLED["']"""),
)


class PreRemediationPackageError(Exception):
    """A generated package's tool module has the pre-remediation shape
    (spec FR-084). Refused outright — never partially loaded, adapted, or
    executed under assumed controls."""


def check_package_shape(tools_source: str, *, package_name: str = "(unknown package)") -> None:
    """Raise `PreRemediationPackageError` if `tools_source` — the text of a
    generated package's `tools.py` — predates this remediation."""
    if _REQUIRED_MARKER not in tools_source or any(
        pattern.search(tools_source) for pattern in _FORBIDDEN_PATTERNS
    ):
        raise PreRemediationPackageError(
            f"'{package_name}' was generated by a pre-remediation version of team_maker "
            f"(its tools.py is missing the mandatory execution policy) and cannot be run. "
            f"Rebuild the package with the current team_maker to pick up mandatory "
            f"sandboxing, mount allowlisting and tool authorization."
        )


def _import_package_module(package_dir: Path, module_name: str) -> Any:
    """Import `module_name` (e.g. "tools") as the generated package itself
    would running standalone: the package directory on `sys.path`, so its
    own top-level `from state_store import ...` resolves exactly like
    `run_example.py`'s does. Stale cache entries are cleared first — a
    previous package resolved earlier in this same long-lived process must
    never shadow this one (`sys.modules` caches by bare name, and every
    generated package uses the same names, "tools" and "state_store").

    Bytecode caching is disabled for the duration: resolving/validating a
    package is not "running" it, and letting Python write a `__pycache__/`
    into the generated package as a side effect pollutes it with a derived
    artifact the user never asked for — found via a broken build
    idempotency test (`.pyc` files are not byte-stable between two builds
    of the same source, since cache invalidation embeds a timestamp/hash)."""
    for name in (module_name, "state_store"):
        sys.modules.pop(name, None)
    package_dir_str = str(package_dir)
    sys.path.insert(0, package_dir_str)
    previous_dont_write_bytecode = sys.dont_write_bytecode
    sys.dont_write_bytecode = True
    try:
        return importlib.import_module(module_name)
    finally:
        sys.dont_write_bytecode = previous_dont_write_bytecode
        sys.path.remove(package_dir_str)
        for name in (module_name, "state_store"):
            sys.modules.pop(name, None)


def _inert_tool(name: str) -> Any:
    """A structurally-real tool instance for the no-package fallback used
    when a `PackageToolResolver` is constructed with `package_path=None`
    (this port's own unit tests build in-memory teams with no package on
    disk — see `tests/unit/adapters/test_crewai_execution_engine.py`'s
    Step 0 oracle). Proves `_build_agent` actually wires `AgentSpec.tools`
    through to a real `Agent.tools` entry; raises `ToolPolicyError` if
    actually invoked, since there is no package execution policy to run it
    under.

    Imports crewai locally, not at module scope — this module is not the
    one exempt directory for that (`adapters/runtime_crewai/`), and the
    guard test only scans top-level imports."""
    from crewai.tools import tool as _tool_decorator

    def _unavailable(*_args: Any, **_kwargs: Any) -> str:
        raise ToolPolicyError(
            f"'{name}' has no package to execute against — this engine was "
            f"constructed without a tool_resolver bound to a built package"
        )

    _unavailable.__doc__ = TOOL_CATALOG[name].description
    return _tool_decorator(name)(_unavailable)


class PackageToolResolver(ToolResolver):
    """The only code that loads a generated package's tool module (FR-024).

    `package_path=None` is the no-package fallback described on
    `_inert_tool` above — every real caller (`runtime/executor.py`) supplies
    an actual built package's directory.

    `key_config` is accepted for wiring-shape parity with
    `contracts/tool-resolver-port.md` and reserved for a future
    tool-credential resolution path; it is currently unused because every
    generated tool that needs a credential reads it directly from the
    process environment at call time (e.g. `git_account_tool`'s
    `GITHUB_TOKEN` lookup) — there is no injection point to resolve *into*
    yet. This resolver still MUST NOT call, alter or duplicate
    `preflight.check_credentials` (FR-022), and does not.
    """

    def __init__(self, package_path: Optional[Path], key_config: Optional[KeyConfig] = None) -> None:
        self._package_path = Path(package_path) if package_path is not None else None
        self._key_config = key_config
        self._registry: Optional[dict[str, Any]] = None

    def resolve(self, name: str) -> ResolvedTool:
        if name not in TOOL_CATALOG:
            raise UnknownToolError(f"'{name}' is not a canonical tool name")

        if self._package_path is None:
            return ResolvedTool(name=name, instance=_inert_tool(name))

        registry = self._load_registry()
        entry = registry.get(name)
        if entry is None:
            raise UnresolvableToolError(
                f"'{name}' is canonical but has no binding in this package's tools.py registry"
            )
        instance = entry[0] if isinstance(entry, list) else entry
        return ResolvedTool(name=name, instance=instance)

    def resolve_all(self, names: Sequence[str]) -> list[ResolvedTool]:
        """As the base class, except a name in `CONDITIONALLY_AVAILABLE_TOOL_NAMES`
        that is genuinely absent from this package's registry — FR-065's
        UNAVAILABLE_HERE, a missing optional dependency or credential, never
        NO_IMPLEMENTATION — is omitted with a warning rather than refusing
        the whole run.

        This is a deliberate, interim posture, not a silent-drop regression
        of RC-5: it applies to exactly the three catalog entries whose own
        codegen binding (`tools.py.j2`) already degrades the same way
        (`if os.environ.get(...): ... else: print("[warn] ... unavailable")`)
        — never to the always-available core set RC-5 was about. Phase 7's
        preflight (T132-T134) is where this becomes a proper, actionable
        hard failure naming the missing prerequisite; that does not exist
        yet, and a Phase 5 hard-crash in its place would refuse every
        package whose optional dependency happens to be absent from
        *team_maker's own* process — not the generated package's, which may
        have installed it separately per its own `requirements.txt` for the
        standalone run path (`crewai-tools` and `PyGithub` are never
        team_maker dependencies themselves — see `pyproject.toml`)."""
        resolved: list[ResolvedTool] = []
        failures: list[str] = []
        for name in names:
            try:
                resolved.append(self.resolve(name))
            except UnresolvableToolError as exc:
                if self._package_path is not None and name in CONDITIONALLY_AVAILABLE_TOOL_NAMES:
                    warnings.warn(
                        f"tool '{name}' is declared but not available in this process "
                        f"(a required optional dependency or credential is absent here) "
                        f"— omitted from this agent's tools rather than refusing the run. "
                        f"Phase 7 preflight will make this an actionable hard failure.",
                        stacklevel=2,
                    )
                    continue
                failures.append(f"{name} ({type(exc).__name__}): {exc}")
            except (UnknownToolError, ToolPolicyError) as exc:
                failures.append(f"{name} ({type(exc).__name__}): {exc}")
        if failures:
            raise UnresolvableToolError(
                "cannot resolve declared tool(s): " + "; ".join(failures)
            )
        return resolved

    def _load_registry(self) -> dict[str, Any]:
        if self._registry is not None:
            return self._registry
        assert self._package_path is not None
        tools_py = self._package_path / "tools.py"
        try:
            source = tools_py.read_text(encoding="utf-8")
        except OSError as exc:
            raise UnresolvableToolError(
                f"could not read {tools_py}: {exc}"
            ) from exc
        check_package_shape(source, package_name=self._package_path.name)
        module = _import_package_module(self._package_path, "tools")
        self._registry = module.TOOL_REGISTRY
        return self._registry
