#!/usr/bin/env bash
# ==============================================================================
# smoke_test.sh — End-to-end smoke test for a team_maker-generated team.
#
# This script is the canonical runbook for verifying that team_maker still
# produces a runnable multi-agent team. It does the full loop: generate,
# install, execute (inside Docker), assert.
#
# What it does
# ------------
#   1. Verifies prerequisites: docker running, python, OPENAI_API_KEY exported.
#   2. Detects whether a Langfuse server is running at LANGFUSE_HOST (default
#      http://localhost:3000) and enables tracing if so.
#   3. Writes a YAML request (3 agents, calculator+stats task, no git, no net).
#   4. Runs `python -m team_maker create` to produce the team package.
#   5. Pulls the sandbox image (`python:3.12-slim`) if missing.
#   6. Installs the generated team's runtime deps into a dedicated venv.
#   7. Runs `run_example.py` with:
#        SANDBOX_ENABLED=true   → risky tool calls execute via `docker run --rm`
#        timeout 300s           → hard cap to prevent runaway token usage
#   8. Asserts post-run state: log non-empty, no git ops, workspace artifacts
#      present and callable (add(2,3)==5, mean([1,2,3])==2.0).
#
# Langfuse tracing
# ----------------
# Start the local Langfuse server before running this script:
#   cd langfuse && docker compose up -d && cd ..
#
# The script auto-detects Langfuse at LANGFUSE_HOST and uses the default
# project keys provisioned by langfuse/docker-compose.yml. Tracing is
# silently skipped if the server is not reachable.
#
# Usage
# -----
#   scripts/smoke_test.sh                 # run the full loop
#   scripts/smoke_test.sh --keep-venv     # keep venv across runs (faster)
#   scripts/smoke_test.sh --no-run        # generate + install only, skip crew
#
# Exit codes
# ----------
#   0  all assertions passed
#   1  prerequisite missing
#   2  generation failed
#   3  install failed
#   4  runner failed or assertions failed
# ==============================================================================

set -euo pipefail

# ---------- config ------------------------------------------------------------

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG="$ROOT/examples/smoke_test.yaml"
TEAM_DIR="$ROOT/generated_teams/smoke_team"
SANDBOX_IMAGE="python:3.12-slim"
RUNNER_TIMEOUT="${RUNNER_TIMEOUT:-300}"

# Langfuse defaults matching langfuse/docker-compose.yml init vars
LANGFUSE_HOST="${LANGFUSE_HOST:-http://127.0.1.1:3000}"
LANGFUSE_PUBLIC_KEY="${LANGFUSE_PUBLIC_KEY:-pk-lf-smoke-team-local}"
LANGFUSE_SECRET_KEY="${LANGFUSE_SECRET_KEY:-sk-lf-smoke-team-local}"

KEEP_VENV=false
SKIP_RUN=false
for arg in "$@"; do
    case "$arg" in
        --keep-venv) KEEP_VENV=true ;;
        --no-run)    SKIP_RUN=true ;;
        *) echo "unknown flag: $arg"; exit 1 ;;
    esac
done

log() { printf '[smoke] %s\n' "$*"; }

# ---------- step 1: prerequisites --------------------------------------------

log "checking prerequisites..."
command -v docker >/dev/null || { log "FAIL: docker not installed"; exit 1; }
command -v python >/dev/null || { log "FAIL: python not installed"; exit 1; }
docker ps >/dev/null 2>&1  || { log "FAIL: docker daemon not reachable"; exit 1; }
[ -n "${OPENAI_API_KEY:-}" ] || { log "FAIL: OPENAI_API_KEY not set"; exit 1; }
log "  docker ok, python $(python --version 2>&1 | cut -d' ' -f2), OPENAI_API_KEY set"

# ---------- step 2: Langfuse detection ---------------------------------------

log "checking for Langfuse observability server..."
if curl -sf "${LANGFUSE_HOST}/api/public/health" >/dev/null 2>&1; then
    log "  ✓ Langfuse detected at $LANGFUSE_HOST — tracing enabled"
    log "    project keys: $LANGFUSE_PUBLIC_KEY"
else
    log "  (Langfuse not reachable at $LANGFUSE_HOST — tracing disabled)"
    log "  to enable: cd langfuse && docker compose up -d && cd .."
    LANGFUSE_PUBLIC_KEY=""
    LANGFUSE_SECRET_KEY=""
fi

# ---------- step 3: write YAML request ---------------------------------------

log "writing YAML request to $CONFIG ..."
mkdir -p "$(dirname "$CONFIG")"
cat > "$CONFIG" <<'YAML'
# Auto-generated by scripts/smoke_test.sh — safe to regenerate.
team_name: "Dev Tools Team"
purpose: >
  Build a small Python utility package in the workspace/ directory.
  Deliver exactly three files:
    1. workspace/calculator.py — functions add(a,b), subtract(a,b), multiply(a,b),
       divide(a,b), each with a one-line docstring.
    2. workspace/stats.py — functions mean(nums), median(nums), min_val(nums),
       max_val(nums) operating on a list of numbers, each with a one-line docstring.
    3. workspace/main.py — imports both modules and prints one demo call per function.
  Use exactly three agents: a spec writer, a code implementer, and a reviewer.
  Each agent may use the code_writer tool to write files. No tests, no extra files.

output_path: "./generated_teams/smoke_team"
stack: "Python 3.12"

planning_llm:
  provider: openai
  model: gpt-4o-mini
  api_key_env: OPENAI_API_KEY

default_llm:
  provider: openai
  model: gpt-4o-mini
  api_key_env: OPENAI_API_KEY

framework: crewai
state_backend: file
overwrite: true

sandbox:
  image: "python:3.12-slim"
  workspace_mount: "./workspace"
  network: none

constraints:
  - "No git operations whatsoever (no clones, no commits, no PRs)"
  - "No network access from inside tools"
  - "Deliver only: workspace/calculator.py, workspace/stats.py, workspace/main.py"
  - "Exactly three agents: spec_writer, code_implementer, reviewer"
YAML

# ---------- step 4: generate team --------------------------------------------

log "generating team via team_maker..."
cd "$ROOT"
if ! python -m team_maker create --config "$CONFIG" --overwrite; then
    log "FAIL: team_maker create exited non-zero"
    exit 2
fi
[ -f "$TEAM_DIR/run_example.py" ] || { log "FAIL: run_example.py missing"; exit 2; }
[ -f "$TEAM_DIR/tools.py" ]       || { log "FAIL: tools.py missing"; exit 2; }
[ -f "$TEAM_DIR/state_store.py" ] || { log "FAIL: state_store.py missing"; exit 2; }

# Hard guard: planner must not wire a git tool for this purpose.
if grep -q 'git_account' "$TEAM_DIR"/agents/*.yaml; then
    log "FAIL: generated agent requested git_account tool despite 'no git' constraint"
    grep -l 'git_account' "$TEAM_DIR"/agents/*.yaml
    exit 2
fi
log "  team generated: $(ls "$TEAM_DIR"/agents | wc -l) agents, $(ls "$TEAM_DIR"/tasks | wc -l) tasks"

# ---------- step 5: pull sandbox image ---------------------------------------

log "ensuring sandbox image $SANDBOX_IMAGE is available..."
if ! docker image inspect "$SANDBOX_IMAGE" >/dev/null 2>&1; then
    docker pull "$SANDBOX_IMAGE"
fi

# ---------- step 6: install runtime deps -------------------------------------

VENV="$TEAM_DIR/.venv"
if $KEEP_VENV && [ -d "$VENV" ]; then
    log "reusing existing venv at $VENV"
else
    log "creating venv at $VENV ..."
    rm -rf "$VENV"
    python -m venv "$VENV"
fi
# shellcheck disable=SC1091
source "$VENV/bin/activate"
log "installing generated team's requirements.txt (this can take a few minutes) ..."
if ! pip install -q --disable-pip-version-check -r "$TEAM_DIR/requirements.txt"; then
    log "FAIL: pip install failed"
    deactivate
    exit 3
fi

# ---------- step 7: run the crew (sandboxed) --------------------------------

if $SKIP_RUN; then
    log "--no-run given; skipping runner."
    deactivate
    log "  ✅ generation + install passed"
    exit 0
fi

mkdir -p "$TEAM_DIR/workspace"
LOG_FILE="$TEAM_DIR/runner.log"

# Check if docker-compose.yml was generated (indicates Ollama sidecar)
if [ -f "$TEAM_DIR/docker-compose.yml" ]; then
    log "running via docker-compose (ollama sidecar, timeout ${RUNNER_TIMEOUT}s) ..."
    log "  → output streamed to $LOG_FILE"
    set +e
    ( cd "$TEAM_DIR" && \
      timeout "$RUNNER_TIMEOUT" \
        env OPENAI_API_KEY="$OPENAI_API_KEY" \
            LANGFUSE_PUBLIC_KEY="$LANGFUSE_PUBLIC_KEY" \
            LANGFUSE_SECRET_KEY="$LANGFUSE_SECRET_KEY" \
            LANGFUSE_HOST="$LANGFUSE_HOST" \
        docker compose up --build \
          --abort-on-container-exit \
          --exit-code-from runner ) 2>&1 | tee "$LOG_FILE"
    RC=${PIPESTATUS[0]}
    ( cd "$TEAM_DIR" && docker compose down ) 2>/dev/null || true
    set -e
else
    log "running run_example.py (SANDBOX_ENABLED=true, timeout ${RUNNER_TIMEOUT}s) ..."
    log "  → output streamed to $LOG_FILE"
    set +e
    ( cd "$TEAM_DIR" && \
      timeout "$RUNNER_TIMEOUT" \
        env SANDBOX_ENABLED=true \
            OPENAI_API_KEY="$OPENAI_API_KEY" \
            LANGFUSE_PUBLIC_KEY="$LANGFUSE_PUBLIC_KEY" \
            LANGFUSE_SECRET_KEY="$LANGFUSE_SECRET_KEY" \
            LANGFUSE_HOST="$LANGFUSE_HOST" \
        python run_example.py ) 2>&1 | tee "$LOG_FILE"
    RC=${PIPESTATUS[0]}
    set -e
fi

deactivate 2>/dev/null || true

# ---------- step 8: assertions ----------------------------------------------

log "checking runner outcome (rc=$RC) ..."
FAIL=false
if [ $RC -eq 124 ]; then
    log "  ⚠ runner hit the ${RUNNER_TIMEOUT}s timeout"
    FAIL=true
elif [ $RC -ne 0 ]; then
    log "  ❌ runner exited with non-zero status $RC"
    FAIL=true
fi

[ -s "$LOG_FILE" ] || { log "  ❌ runner.log is empty"; FAIL=true; }

if grep -q -E '(git clone|git init|git commit|git push|create_repo|create_pr)' "$LOG_FILE"; then
    log "  ❌ runner log contains git operations — constraint violated"
    FAIL=true
fi

if ! grep -q -E '(RESULT|result|calculator|stats)' "$LOG_FILE"; then
    log "  ⚠ no obvious result banner in log — agents may not have completed"
fi

# Assert workspace/calculator.py
CALC_PY="$TEAM_DIR/workspace/calculator.py"
if [ ! -f "$CALC_PY" ]; then
    log "  ❌ workspace/calculator.py was not created — artifact persistence failed"
    FAIL=true
else
    log "  ✓ workspace/calculator.py exists"
    python - "$CALC_PY" <<'EOF'
import sys, importlib.util
spec = importlib.util.spec_from_file_location("calculator", sys.argv[1])
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)
assert hasattr(mod, "add"), "calculator.py must define add()"
result = mod.add(2, 3)
assert result == 5, f"add(2, 3) returned {result!r}, expected 5"
print("  ✓ add(2, 3) == 5")
EOF
    if [ $? -ne 0 ]; then
        log "  ❌ calculator.py verification failed"
        FAIL=true
    fi
fi

# Assert workspace/stats.py
STATS_PY="$TEAM_DIR/workspace/stats.py"
if [ ! -f "$STATS_PY" ]; then
    log "  ❌ workspace/stats.py was not created — artifact persistence failed"
    FAIL=true
else
    log "  ✓ workspace/stats.py exists"
    python - "$STATS_PY" <<'EOF'
import sys, importlib.util
spec = importlib.util.spec_from_file_location("stats", sys.argv[1])
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)
assert hasattr(mod, "mean"), "stats.py must define mean()"
result = mod.mean([1, 2, 3])
assert result == 2.0, f"mean([1,2,3]) returned {result!r}, expected 2.0"
print("  ✓ mean([1, 2, 3]) == 2.0")
EOF
    if [ $? -ne 0 ]; then
        log "  ❌ stats.py verification failed"
        FAIL=true
    fi
fi

if $FAIL; then
    log "❌ smoke test failed"
    exit 4
fi

log "✅ smoke test passed"
if [ -n "${LANGFUSE_PUBLIC_KEY:-}" ]; then
    log "   traces → $LANGFUSE_HOST  (project: smoke-team)"
fi
