#!/usr/bin/env bash
# ==============================================================================
# smoke_test.sh — End-to-end smoke test for a team_maker-generated team.
#
# This script is the canonical runbook for verifying that team_maker still
# produces a runnable multi-agent team. It does the full loop: generate,
# install, execute (inside Docker), assert.
#
# What it does
# ------------
#   1. Verifies prerequisites: docker running, python, OPENAI_API_KEY exported.
#   2. Writes a minimal YAML request (2 agents, trivial task, no git, no net).
#   3. Runs `python -m team_maker create` to produce the team package.
#   4. Pulls the sandbox image (`python:3.12-slim`) if missing.
#   5. Installs the generated team's runtime deps into a dedicated venv.
#   6. Runs `run_example.py` with:
#        SANDBOX_ENABLED=true   → risky tool calls execute via `docker run --rm`
#        timeout 300s           → hard cap to prevent runaway token usage
#   7. Asserts post-run state: non-zero log, "--- RESULT ---" banner, no
#      git operations, workspace dir is present.
#
# Why Docker
# ----------
# Every shell / filesystem / docker_runner tool the agents call is wrapped in
# `_run_sandboxed()` inside the generated `tools.py`. When SANDBOX_ENABLED=true
# that wrapper dispatches through:
#     docker run --rm --network <net> -v <workspace>:/workspace <image> sh -c ...
# so untrusted LLM-generated commands never touch the host filesystem.
#
# Token discipline
# ----------------
#   * Planner + runtime both use `gpt-4o-mini` (cheapest OpenAI model).
#   * Purpose is deliberately tight; constraints forbid git and network.
#   * Timeout 300 s caps the absolute worst case at a few thousand tokens.
#
# Usage
# -----
#   scripts/smoke_test.sh                 # run the full loop
#   scripts/smoke_test.sh --keep-venv     # keep venv across runs (faster)
#   scripts/smoke_test.sh --no-run        # generate + install only, skip crew
#
# Exit codes
# ----------
#   0  all assertions passed
#   1  prerequisite missing
#   2  generation failed
#   3  install failed
#   4  runner failed or assertions failed
# ==============================================================================

set -euo pipefail

# ---------- config ------------------------------------------------------------

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG="$ROOT/examples/smoke_test.yaml"
TEAM_DIR="$ROOT/generated_teams/smoke_team"
SANDBOX_IMAGE="python:3.12-slim"
RUNNER_TIMEOUT="${RUNNER_TIMEOUT:-300}"

KEEP_VENV=false
SKIP_RUN=false
for arg in "$@"; do
    case "$arg" in
        --keep-venv) KEEP_VENV=true ;;
        --no-run)    SKIP_RUN=true ;;
        *) echo "unknown flag: $arg"; exit 1 ;;
    esac
done

log() { printf '[smoke] %s\n' "$*"; }

# ---------- step 1: prerequisites --------------------------------------------

log "checking prerequisites..."
command -v docker >/dev/null || { log "FAIL: docker not installed"; exit 1; }
command -v python >/dev/null || { log "FAIL: python not installed"; exit 1; }
docker ps >/dev/null 2>&1  || { log "FAIL: docker daemon not reachable"; exit 1; }
[ -n "${OPENAI_API_KEY:-}" ] || { log "FAIL: OPENAI_API_KEY not set"; exit 1; }
log "  docker ok, python $(python --version 2>&1 | cut -d' ' -f2), OPENAI_API_KEY set"

# ---------- step 2: write YAML request ---------------------------------------

log "writing YAML request to $CONFIG ..."
mkdir -p "$(dirname "$CONFIG")"
cat > "$CONFIG" <<'YAML'
# Auto-generated by scripts/smoke_test.sh — safe to regenerate.
team_name: "Smoke Team"
purpose: >
  Produce a single Python file hello.py in the workspace that defines
  a function add(a, b) returning a + b, plus a brief docstring. No tests,
  no dependencies, no network calls, no git operations. Keep the work
  minimal — two LLM turns per agent is enough.

output_path: "./generated_teams/smoke_team"
stack: "Python 3.12"

planning_llm:
  provider: openai
  model: gpt-4o-mini
  api_key_env: OPENAI_API_KEY

default_llm:
  provider: ollama
  model: hermes3:3b
  base_url: http://localhost:11434

framework: crewai
state_backend: file
overwrite: true

sandbox:
  image: "python:3.12-slim"
  workspace_mount: "./generated_teams/smoke_team/workspace"
  network: none

constraints:
  - "No git operations whatsoever (no clones, no commits, no PRs)"
  - "No network access from inside tools"
  - "Exactly one deliverable file named hello.py"
  - "Two agents maximum"
YAML

# ---------- step 3: generate team --------------------------------------------

log "generating team via team_maker..."
cd "$ROOT"
if ! python -m team_maker create --config "$CONFIG" --overwrite; then
    log "FAIL: team_maker create exited non-zero"
    exit 2
fi
[ -f "$TEAM_DIR/run_example.py" ] || { log "FAIL: run_example.py missing"; exit 2; }
[ -f "$TEAM_DIR/tools.py" ]       || { log "FAIL: tools.py missing"; exit 2; }
[ -f "$TEAM_DIR/state_store.py" ] || { log "FAIL: state_store.py missing"; exit 2; }

# Hard guard: planner must not wire a git tool for this purpose.
if grep -q 'git_account' "$TEAM_DIR"/agents/*.yaml; then
    log "FAIL: generated agent requested git_account tool despite 'no git' constraint"
    grep -l 'git_account' "$TEAM_DIR"/agents/*.yaml
    exit 2
fi
log "  team generated: $(ls "$TEAM_DIR"/agents | wc -l) agents, $(ls "$TEAM_DIR"/tasks | wc -l) tasks"

# ---------- step 4: pull sandbox image ---------------------------------------

log "ensuring sandbox image $SANDBOX_IMAGE is available..."
if ! docker image inspect "$SANDBOX_IMAGE" >/dev/null 2>&1; then
    docker pull "$SANDBOX_IMAGE"
fi

# ---------- step 5: install runtime deps -------------------------------------

VENV="$TEAM_DIR/.venv"
if $KEEP_VENV && [ -d "$VENV" ]; then
    log "reusing existing venv at $VENV"
else
    log "creating venv at $VENV ..."
    rm -rf "$VENV"
    python -m venv "$VENV"
fi
# shellcheck disable=SC1091
source "$VENV/bin/activate"
log "installing generated team's requirements.txt (this can take a few minutes) ..."
if ! pip install -q --disable-pip-version-check -r "$TEAM_DIR/requirements.txt"; then
    log "FAIL: pip install failed"
    deactivate
    exit 3
fi

# ---------- step 6: run the crew (sandboxed) --------------------------------

if $SKIP_RUN; then
    log "--no-run given; skipping runner."
    deactivate
    log "  ✅ generation + install passed"
    exit 0
fi

mkdir -p "$TEAM_DIR/workspace"
LOG_FILE="$TEAM_DIR/runner.log"
log "running run_example.py (SANDBOX_ENABLED=true, timeout ${RUNNER_TIMEOUT}s) ..."
log "  → output streamed to $LOG_FILE"

set +e
( cd "$TEAM_DIR" && \
  timeout "$RUNNER_TIMEOUT" \
    env SANDBOX_ENABLED=true OPENAI_API_KEY="$OPENAI_API_KEY" \
    python run_example.py ) 2>&1 | tee "$LOG_FILE"
RC=${PIPESTATUS[0]}
set -e
deactivate

# ---------- step 7: assertions ----------------------------------------------

log "checking runner outcome (rc=$RC) ..."
FAIL=false
if [ $RC -eq 124 ]; then
    log "  ⚠ runner hit the ${RUNNER_TIMEOUT}s timeout"
    FAIL=true
elif [ $RC -ne 0 ]; then
    log "  ❌ runner exited with non-zero status $RC"
    FAIL=true
fi

[ -s "$LOG_FILE" ] || { log "  ❌ runner.log is empty"; FAIL=true; }

if grep -q -E '(git clone|git init|git commit|git push|create_repo|create_pr)' "$LOG_FILE"; then
    log "  ❌ runner log contains git operations — constraint violated"
    FAIL=true
fi

if ! grep -q -E '(RESULT|result|hello)' "$LOG_FILE"; then
    log "  ⚠ no obvious result banner in log — agents may not have completed"
fi

HELLO_PY="$TEAM_DIR/workspace/hello.py"
if [ ! -f "$HELLO_PY" ]; then
    log "  ❌ workspace/hello.py was not created — artifact persistence failed"
    FAIL=true
else
    log "  ✓ workspace/hello.py exists"
    python - "$HELLO_PY" <<'EOF'
import sys, importlib.util
spec = importlib.util.spec_from_file_location("hello", sys.argv[1])
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)
assert hasattr(mod, "add"), "hello.py must define add()"
result = mod.add(2, 3)
assert result == 5, f"add(2, 3) returned {result}, expected 5"
print("  ✓ add(2, 3) == 5")
EOF
    if [ $? -ne 0 ]; then
        log "  ❌ add(2, 3) verification failed"
        FAIL=true
    fi
fi

if $FAIL; then
    log "❌ smoke test failed"
    exit 4
fi

log "✅ smoke test passed"
